### ISSUE TITLE
Extra digit of precision for the lat/lon label?

### ISSUE THREAD

**Issue by Cmjstealth** [jaybo/deepzoom-blog#14]
Might be handy to have one extra digit of precision for the lat/lon location. 0.0001 degrees of latitude, in the current implementation, is about 40 ft. This would be useful for navigating to more specific spots when locating anchor sites, dive sites, etc.

Example: show 47.59408, -122.48198 instead of 47.5940, -122.4820

![Screenshot 2023-02-01 164813](https://user-images.githubusercontent.com/124218418/216203512-273a334a-573d-43b9-afa7-0127a6a781a3.jpg)

**Comment by jaybo** [comment]
5 digits of decimal precision will show up in the next release.  Thanks for the suggestion.

**Comment by Cmjstealth** [comment]
That's awesome!

Is there by chance an existing way to search or otherwise move the map to a specific lat/lon? Consider the use case of entering a marker for a known coordinate, for example.

**Comment by jaybo** [comment]
The next version will allow you to search for either a named location or a Lat Lng

![image](https://user-images.githubusercontent.com/1607323/216754927-5fe9d12d-2537-40cc-87bc-01274b0728b9.png)

**Comment by jaybo** [comment]
Obligatory XKCD image:
![image](https://user-images.githubusercontent.com/1607323/218269260-00b8b153-2369-4c69-ab7e-67c0bfa46dbd.png)

**Comment by Cmjstealth** [comment]
Awesome! Search works with my coordinates now too!
