### ISSUE TITLE
DeepZoom Club not Recognized

### ISSUE THREAD

**Issue by Billy-Roy** [jaybo/deepzoom-blog#35]
I wanted to support your fine efforts so I joined the club using Apple Pay. But the app doesn’t recognize the purchase and I still see the annoying ad requesting I join. Should I reverse the payment and try again or what?

**Comment by jaybo** [comment]
Hi,
Please check the following:

**1. Confirm you are  logged in.** 
Open the hamburger menu (very top left on both mobile and desktop).  At the very top it should show your avatar or initials. If not, log in.
![image](https://github.com/jaybo/deepzoom-blog/assets/1607323/d224a623-c359-44ea-b3bf-459f6fbd326f)

**2. Verify you're subscribed.** 
Click the "Account" button next to your avatar. If subscribed, there should be a button labeled "Manage your subscription". If not subscribed, there will be a button "Join the DeepZoom club!".

**Comment by Billy-Roy** [comment]
Hey Jay,

Thanks for following up on this. I have subscribed, and logged in, but it still shows the "Join the DeepZoom Club" option. That's the challenging I'm trying to work around.

![Screenshot 2023-12-12 at 7 24 08 AM](https://github.com/jaybo/deepzoom-blog/assets/152095022/b4673994-3c2d-49e1-9ebb-7706faf4ef93)

**Comment by jaybo** [comment]
Sorry for the delay responding...

I looked at the list of subscribers from Stripe (the company which handles card processing), but didn't find a subscription that looks like yours.  Do you have any kind of transaction ID?  What was the date of the transaction?  What are the first few letters of the email used?

Thanks, Jay

**Comment by Billy-Roy** [comment]
Jay,

I paid using Apple Pay on 11/22/23. I don't know if they hide the email or not, but you can try (wre...)

Bill
