### ISSUE TITLE
Map / tile error - Washington > Whidbey Island > Coupeville

### ISSUE THREAD

**Issue by PugetSoundSailor** [jaybo/deepzoom-blog#38]
Apologies if this isn't the right place to report this. When I zoom into Coupeville on Washington State's Whidbey Island, the map disappears and another map's narratives show up. See screenshot below.

<img width="773" alt="Screenshot 2024-01-06 at 3 03 41 PM" src="https://github.com/jaybo/deepzoom-blog/assets/155855517/8d6c73a9-dd95-48e0-8484-8e3ba3bb13dc">

**Comment by jaybo** [comment]
Sorry, yes, this has been a longstanding issue.  A new release of DeepZoom with updated NOAA charts is imminent (probably February or before 🤞).  This will include "cutouts" for land masses.  Unfortunately, the traditional raster based charts are no longer being updated by NOAA, so the artistry of the older style charts will be lost.  But I think the combination of Mapbox satellite and street maps merged with the new NOAA rendition looks generally pleasing.

![image](https://github.com/jaybo/deepzoom-blog/assets/1607323/4459c7b6-0304-425f-81cb-e44030c94b63)

![image](https://github.com/jaybo/deepzoom-blog/assets/1607323/018a714d-1e13-485b-a83b-3c22204788a2)

**Comment by PugetSoundSailor** [comment]
I'm following, and the new vector charts look clean (but lack the spirit of the raster ones). DeepZoom is a wonderful resource--thank you for all that you do Jay.
