### ISSUE TITLE
weather icons not available

### ISSUE THREAD

**Issue by mdwkyk** [jaybo/deepzoom-blog#39]
Hi there! I'm on a 2023 MacBook Pro, Ventura, running Safari 17.2.1. I am logged in to my DZ account. A millisecond after DeepZoom loads, the three weather icons disappear. I can't get to them fast enough so I can't add wind, temp or precipitation to my layers. My weather text slider under layers is up at 1 (max). I have set the zooms for hiding weather and wind streams at the max (20) just in case this was affecting something (I think this should affect layer visibility, not the icons themselves?). I have had mixed success with Firefox (sometimes the weather icons are there but sometimes not, and sometimes when they are there the data in the little rectangles next to the circular icons don't seem to change as I move the map around, like they are not actually updating against any real data). Is there yet another browser I should use specifically for DZ (I always use Safari but can definitely adopt this strategy)? This is an amazing tool and resource - thank you so much!

**Comment by jaybo** [comment]
Hi!  The weather data (buttons and data) only show up if animation **time** is within the forecast period.  I'm guessing that you have at some point loaded a trip which has a fixed start time from the past.  Here are 3 different ways to fix this.

1. Click or tap on the time display and you'll see options of when you want the animation to start and for how long.  If you just click **Now** button you'll weather for the current moment.  Or choose **3 Days** and  pick the start day from the calendar.

    <img width="189" alt="image" src="https://github.com/jaybo/deepzoom-blog/assets/1607323/150b409c-3ee6-435c-ae1a-295d1679a42f">

2. Click **Trip.New** on the Trip page.  This resets the timebase to 1 Day, beginning today.

3. Assuming you have one or more routes created as part of your trip, go to the Trips page and click **Depart.Today**.  All routes will be time shifted with the earliest route starting today.


DeepZoom should be browser agnostic.

**Comment by mdwkyk** [comment]
I can't thank you enough for taking the time to reply! I will have time in the next several days to work through these steps - wanted to let you know I'd seen the suggestions and am grateful. :)

**Comment by mdwkyk** [comment]
Ok, I will admit that I'm not sure I fully follow your explanations above, but I think what I did come to understand is that there are weather forecasts for today and 2 more days out (i.e., the "forecast period"). So if I set the trip/animation date anytime in those three days, I get the buttons. Since I was planning a demo trip for our youth group for July 2024 (the far future, not the past), there is of course no way to have accurate weather data (duh). I think because I had been playing with the DeepZoom trip planning features while I happened to be in this future timeframe, I wasn't thinking about the fact that weather wouldn't be available. So I can plan trips relative to currents as far in the future as I want, and then use weather data in DeepZoom a couple of days out to re-assess. 

I think this explains why sometimes it did and didn't work in Firefox - I was sometimes in my saved trip and sometimes must have been in a new/unsaved trip starting that day. I'd also tried it on my husband's PC and had the weather available. I must have just opened it without going to my July 2024 trip. Do you think I am interpreting all this correctly? Thank you, thank you, thank you!

**Comment by jaybo** [comment]
Yes.  I think you've got it.
