### ISSUE TITLE
White band at right side of DeepZoom display

### ISSUE THREAD

**Issue by Dougpalm** [jaybo/deepzoom-blog#40]
I’ve refreshed to the new version 3.14.35 version of DeepZoom on my iPad Pro (first generation, iOS 16.7.6).  

While it seems to start up fine, after a few moments a white band appears at the right side of the screen.  I’ve enclosed a picture to show what’s happening. 

I don’t have this problem on my iPhone. @
![IMG_9675](https://github.com/jaybo/deepzoom-blog/assets/104842171/1ad6db82-3b0a-4b67-9681-0e155e57db7f)

**Comment by jaybo** [comment]
I also have an iPad Pro (11", 3d gen), and can't directly replicate this.  Are you sure you didn't hit the three white dots at the top of the screen which puts it into split screen mode?

If you rotate the screen 90 degrees, and then 90 degrees back, does the issue get resolved?

**Comment by Dougpalm** [comment]
Jay,No, it wasn’t split screen or slide over or other window management maneuver.  DeepZoom would come up fine on the ipad for a few moments then spontaneously the white band would appear at the right, shoving everything else to the left.Right after I posted the trouble ticket the same thing started happening on my phone, except worse.  Deepzoom would only open with an entirely white screen and no other content.  Multiple shutdowns and restarts of the DeepZoom PWA would not solve the problem.Now it’s all fine, however.  Both the ipad and the iphone are running the new DeepZoom just fine.  I didn’t do anything other than wait it out. I’ll let you know if it happens again.With everything working normally now I can see some great improvements in DeepZoom. The biggest is the smoother way of creating and editing routes on the iphone and ipad.  In the old version of DeepZoom this process was often jerky and tedious because a chosen waypoint would not immediately snap to the desired location, instead drifting lazily until it seemingly ran out of momentum.  The new version is very responsive in this regard.  In general, I like the use of the newer charts but I do find it harder to read the labels on aids to navigation and lights.  The new version just doesn’t display those as clearly as the old version and when I zoom in to try to read a label it doesn’t always get much clearer in many cases. The issue seems to be a combination of the thin font they are using and the mobile nature of the labels now. It’s a bit like playing Whack-a-Mole sometimes, with the label shifting around and behind other things as you zoom in closer.I do miss the old “edit” button in the route details window but I’m getting used to the new approach of clicking on the route then clicking on the route icon in order to drag the waypoints directly.  I’m not 100% on the new process but I can get it to work after a bit of trial and error.One new problem I’m having with route editing is that every once in a while I must be hitting the trash can icon accidentally.  I don’t recall having that problem with the old version.  Unlike the split feature, which asks if you really want to split a route, the trash can icon doesn’t ask - it just deletes the route.  Without an undo feature to roll back accidental deletes I find I need to be extra careful to save the trip every time before I start to edit a route.Doug ***@***.*** Mar 20, 2024, at 20:19, Jay Borseth ***@***.***> wrote:﻿
I also have an iPad Pro (11", 3d gen), and can't directly replicate this.  Are you sure you didn't hit the three white dots at the top of the screen which puts it into split screen mode?
If you rotate the screen 90 degrees, and then 90 degrees back, does the issue get resolved?

**Comment by jaybo** [comment]
Clarification on one point: Hitting the trash can icon connected to a waypoint only deletes the waypoint (perhaps by accident), and not the whole route, correct?

I have a list of issues regarding the new vector charts which I believe includes the problems you list above.  Please add any other items you discover.
https://github.com/jaybo/deepzoom-blog/issues/37

**Comment by Dougpalm** [comment]
That is true about the trash can next to a selected waypoint. It deletes the selected waypoint instantly and without confirmation. However, I'm thinking of a different trash can button. I'm somehow activating the trash can in the new route adding window. That's the little box that appears at the top of the screen when you hit the button that looks like the bent line with a plus next to it. That route delete trash can is to the right of the plus there. I guess that from time to time the tip of my finger sometimes activates that unforgiving trash can instead of the +. So instead of adding a new route I'm sometimes accidentally deleting the one selected. I am trying to be extra careful not to hit that trash can but it would be nice if it would be more civilized and act like the trip delete trash can or the waypoint/route split icons. In my opinion, if there is no undo option then any trash can button should have an "are you sure" prompt. Doug ***@***.*** Mar 20, 2024, at 10:01 PM, Jay Borseth ***@***.***> wrote:﻿
Clarification on one point: Hitting the trash can icon connected to a waypoint only deletes the waypoint (perhaps by accident), and not the whole route, correct?
I have a list of issues regarding the new vector charts which I believe includes the problems you list above.  Please add any other items you discover.
#37

**Comment by jaybo** [comment]
Great points.  The next version will require confirmation on all route deletions.
