### ISSUE TITLE
Temperature in degrees C not working

### ISSUE THREAD

**Issue by BW-Vancouver** [jaybo/deepzoom-blog#44]
It's showing the temp in degrees F but with the deg C symbol when degrees in C is selected in the Settings

![image](https://github.com/user-attachments/assets/287a6eea-6f6c-40c6-8121-6f4836a1554e)

**Comment by jaybo** [comment]
Thanks for the bug report.  This will be fixed in the next release.

**Comment by jaybo** [comment]
Fixed in 3.14.93
