### ISSUE TITLE
As opposed to current stations, only one tide station is updating when time slider is moved

### ISSUE THREAD

**Issue by Dougpalm** [jaybo/deepzoom-blog#5]
While DeepZoom shows changes at all visible current stations as the time slider moves, it only updates changes at the last tide station selected.  If you identify several tide stations of interest by clicking on them, you can see the tide heights at each for that moment.  However, only the last tide station clicked will show change as the time slider is moved.  All the other tide stations previously clicked remain at their last viewed values, unless one of them is clicked to update it.  If DeepZoom can show the changes at once for all the current stations visible in a view, why not the changes at tide stations as well? Or at least for the tide stations the user has expressed interest in by clicking on them?

**Comment by jaybo** [comment]
The decision to show dynamic current values for all visible stations but not for all tidal stations was made mainly to decrease visual clutter and because I, as a sailor, really only cared about tides at single locations when deciding where to anchor, or when to go clam digging.  I couldn't really come up with a use case for showing multiple dynamic tidal stations.  What's yours?

A secondary issue is:  How do you maintain the list of selected tide stations?  If clicking adds a tide station to the dynamic list, how do you clear the dynamic list?

**Comment by Dougpalm** [comment]
Jay,

Thank you for your reply. 

As a sea kayaker I like knowing not only what the currents are doing over time but also what is happening at different tide stations in an area. 

The way DeepZoom works now, when I select a tide station it displays the tide level for that station as a numerical value.  If I adjust the time slider, the value changes accordingly.

If I then click on a different tide station, however, DeepZoom displays the numerical tide result for that station while the value for the first tide station selected remains visible in a smaller size and frozen at the value it displayed before the second station was clicked.   

This behavior continues if you keep selecting tide stations.  In other words, the values of the previously selected tide stations remain frozen and only the most recently clicked tide station updates. 

In other words, after having consecutively selected a number of tide stations, if you then move the time slider, only the value of the most recently selected tide station updates while all the displayed tide values for the previously selected tide stations are frozen at the values they each had when the focus was on them.  

As compared to the dynamic and simultaneous updating of all displayed current station information in response to time slider adjustments, DeepZoom's inconsistent display of data for multiple tide station seems puzzling and potentially problematic. 

It seems there is a risk someone could miss the fact the previously selected stations displayed are not updating along with the presently selected station, especially as the time slider is adjusted.  Attached is a short video of the problem.  Notice how the tide at Port Townsend changes dynamically while selected stations elsewhere remain frozen.   

If all the tide stations simply displayed their values as dynamically as the current stations do, that would seem more helpful and less prone to misinterpretation. 

Doug Palm
***@***.***

**Comment by jaybo** [comment]
OK, I finally see the issue.  I've fixed the problem of previously (but not currently) selected tide stations showing old results as time changes.  Instead, non-selected tide stations don't show **any** value.  This fix will be in the next release (should be in a week or so).

But making all previously selected tide stations update all at once is a fair bit of work and I'm currently working on other issues so I'm going to punt this for now.

**Comment by jaybo** [comment]
Fixed the problem of previously (but not currently) selected tide stations showing old results as time changes. Instead, non-selected tide stations don't show any value.  Fixed in V2.5.0.

**Comment by Dougpalm** [comment]
Jay,

Fair enough, thanks for your consideration on the matter of dynamic tide info display for all or just multiple selected stations.

I’ve been trying the trip planning features and not having much luck using an iPad or an iPhone (both using Safari and the latest iOS). Should I be using a computer with DeepZoom instead of a mobile device?  And if so, which browser is best for DeepZoom? Maybe Safari and FireFox on iPad and iPhone are not the right browser choices?

Doug Palm
***@***.***

**Comment by jaybo** [comment]
Hi Doug,

In general, a desktop with any browser is definitely easier that a phone, just because you adjust things more easily.  I’d appreciate any feedback on how to improve the experience.  What steps do you find confusing or difficult?

Safari on an iPad should work fine.

Jay

**Comment by Dougpalm** [comment]
﻿It’s been a while since I tried to use DeepZoom for anything other than current and tide predictions. It’s great for that purpose but while I can see the potential for DeepZoom to be used for more sophisticated route planning, getting it to do so seems impractical due to the general unresponsiveness of the interface.For example, I can start a route but there seems to be no way to name it or save it.  It appears the program intends to allow for this but it just isn’t possible.  For example, the name field simply does not accept any text. Other controls are equally unresponsive.  If I want to edit a waypoint, it can’t be selected.  If I want to delete it, it can’t be deleted. Most frustrating, there is no “undo” feature to reverse mistakes. As far as I can get is to click out a route.  That seems to work more smoothly today than it did six months ago. Beyond that, the route can’t I just logged back in and tried to set up a route for a sea kayaking trip. While it was fairly simple to click out waypoints and see a route plot out on the screen, it was impossible to name the route or save it in any way. It’s like the field for the route name does not respond to text entry. In any way.  So any route I try to enter can only be used in the moment.  It can’t be named or saved.Doug ***@***.*** Oct 11, 2022, at 9:03 PM, Jay Borseth ***@***.***> wrote:﻿
Hi Doug,



In general, a desktop with any browser is definitely easier that a phone, just because you adjust things more easily.  I’d appreciate any feedback on how to improve the experience.  What steps do you find confusing or difficult?



Safari on an iPad should work fine.



Jay



From: ***@***.***>

Sent: Tuesday, October 11, 2022 12:03 AM

To: ***@***.***>

Cc: Jay ***@***.***>; State ***@***.***>

Subject: Re: [jaybo/deepzoom-blog] As opposed to current stations, only one tide station is updating when time slider is moved (Issue #5)



Jay,



Fair enough, thanks for your consideration on the matter of dynamic tide info display for all or just multiple selected stations.



I’ve been trying the trip planning features and not having much luck using an iPad or an iPhone (both using Safari and the latest iOS). Should I be using a computer with DeepZoom instead of a mobile device? And if so, which browser is best for DeepZoom? Maybe Safari and FireFox on iPad and iPhone are not the right browser choices?



Doug Palm

***@***.***

**Comment by jaybo** [comment]
Hi Doug,

You save Trips, not routes.  A trip contains one or more routes.

To rename a route, click the little pencil at the end of the name.

![rename](https://user-images.githubusercontent.com/1607323/202888822-f654a736-ee74-4a31-a0df-c13b32c5ac2d.png)

To edit a route, click the edit button on the Routes tab.  Then click on a route to select it,
Then click on a waypoint to select it.  Once you do this, the snip and delete icons appear.

![delete](https://user-images.githubusercontent.com/1607323/202889001-4cfdce87-3336-4537-b4e9-90078858cc83.png)

**Comment by Dougpalm** [comment]
Thank you. I knew those things already but was having trouble getting the program to work consistently. After reading your comments I realized I was not hitting the New button enough times. Here’s the workflow I’ve found works best for building a trip:TripsNewSave[enter new trip name][check Kayak]SaveRoutesNew (don't try to enter a route name here, the name field won’t accept a name and the pencil button will not work)Chose New again[draw out route]Chose New again (so you can give the route you just drew out a name)Click pencil icon[enter route name]OK[adjust date and time settings as needed]To continue adding routes:New[draw out next route]Chose New againClick pencil icon[enter route name]OK[adjust date and time settings as needed]Repeat until done with all routes then click the Done button in the area above the chart. Go back to the Trips tab and click Save to save the trip and all its routes. Click Save again to confirm. If promoted that you have not saved a trip, go back and save it again. If a route appears out of sequence with the other routes, check the start and end times of each route to make sure they line up correctly. Be sure to go back to Trips and click Save to make sure all changes to routes are preserved.Now on to a different matter.Editing the route lines is a somewhat awkward process because of the slow way the program responds to changes.  When I want to move or delete a waypoint in the selected route, the action works something like a cross between an air hockey puck and a ouija board.  Any slight movement of a waypoint causes it to drift off on its own rather than moving precisely where I point. When this happens all I can do is watch the ghostly action until the point comes to a complete stop.  In other words, great care is needed when moving a point so it doesn’t take off and start drifting off on its own to the wrong place. With patience I can get waypoints to move where I want as long as I make the adjustments in very small steps and wait for the ghostly movement to stop before making another small adjustment. Because of all this, I find its often easier to just delete a route and start over rather than trying to edit it.In any case, I’m now getting more out of DeepZoom than before. Thank you for your efforts to make it an even better tool for trip planning.Doug ***@***.*** Nov 19, 2022, at 10:27 PM, Jay Borseth ***@***.***> wrote:﻿
Hi Doug,
You save Trips, not routes.  A trip contains one or more routes.
To rename a route, click the little pencil at the end of the name.

To edit a route, click the edit button on the Routes tab.  Then click on a route to select it,
Then click on a waypoint to select it.  Once you do this, the snip and delete icons appear.

**Comment by jaybo** [comment]
Here's the order I typically use:

- Trip.New
- Route.New
  -- Create a route.  Double click to finish.  Rename route if desired.  Adjust times if desired.
- Route.New
  -- Create a route.  Double click to finish.  Rename route if desired.  Adjust times if desired.
- Route.Edit
  -- Edit any of the already created routes.
- Trip.Save  Name the route you're saving, along with Kayak type.

Regarding sluggishness of updates when editing:  
Q1. What device are you using?
Q2. Is 3D on?  Try turning off if so.

**Comment by Dougpalm** [comment]
Thank you.  I’m having success with my approach and I seem to be on a roll.To prepare trip plans with Deepzoom I’m using an original Apple iPad Pro 12.9 inch with the latest version of iOS and the Safari web browser.  I also use an Apple iPhone but find it easier to work on the bigger screen of the iPad.I’m using Deepzoom in the 2D and Map mode. I’ve tried toggling various settings on and off to see if there is any improvement but so far nothing seems to make editing waypoints a smoother experience.  I am getting used to the way it works, though.  As long as I drag a point very slowly to the place I want it to be and then hold my finger three until the point catches up it seems to work OK.At this point I’ve created a number of trips in DeepZoom and they seem to match well with the results I’ve obtained using other methods. Doug ***@***.*** Nov 20, 2022, at 11:07 PM, Jay Borseth ***@***.***> wrote:﻿
Here's the order I typically use:

Trip.New
Route.New
-- Create a route.  Double click to finish.  Rename route if desired.  Adjust times if desired.
Route.New
-- Create a route.  Double click to finish.  Rename route if desired.  Adjust times if desired.
Route.Edit
-- Edit any of the already created routes.
Trip.Save  Name the route you're saving, along with Kayak type.

Regarding sluggishness of updates when editing:
Q1. What device are you using?
Q2. Is 3D on?  Try turning off if so.

**Comment by jaybo** [comment]
Your pictures didn't come through, but is this the time control you're referencing?

![time](https://user-images.githubusercontent.com/1607323/203163217-b0f3ffa2-5013-4698-acbf-efff7aa7a9c1.png)

I'm able to run through all time settings...

Also, can you confirm you're running the latest version:  2.7.23.

**Comment by jaybo** [comment]
Also, which version of Safari are you running.  Sounds like there were WebGL problems in some Safari versions.
https://bugs.webkit.org/show_bug.cgi?id=230749
https://developer.apple.com/forums/thread/681058

Have you tried DeepZoom with Chrome?

**Comment by Dougpalm** [comment]
Yes, I'm using the latest version of DeepZoom (2.7.23) and that dial is the problematic control for my iPhone 14 Pro Max on iOS 16.1. That dial only shows PM when the hour hand is at 12 position. Move the dial past 12 and the PM switches back to AM.  While I can click AM or PM on that dial, the setting is not preserved when I get back to the Route page. So the best way for me to set the time is to forget the dial altogether and use the time slider on the Route page. Doug ***@***.*** Nov 21, 2022, at 1:43 PM, Jay Borseth ***@***.***> wrote:﻿
Your pictures didn't come through, but is this the time control you're referencing?

I'm able to run through all time settings...
Also, can you confirm you're running the latest version:  2.7.23.

**Comment by Dougpalm** [comment]
Hope you saw my last response to your question about the time dial. I missed seeing your question about the version of safari but it has the same number as the iOS version, namely 16.1.  I see there is a new update 16.1.1 so I'll try that and if it fixes the problem I'll let you know. I've tired Chrome and FireFox with DeepZoom in the past and they offered no advantages over Safari. I prefer to stick with Safari in any case; I trust Apple over the alternatives. Doug ***@***.*** Nov 21, 2022, at 2:13 PM, Jay Borseth ***@***.***> wrote:﻿
Also, which version of Safari are you running.  Sounds like there were WebGL problems in some Safari versions.
https://bugs.webkit.org/show_bug.cgi?id=230749
https://developer.apple.com/forums/thread/681058
Have you tried DeepZoom with Chrome?

**Comment by Dougpalm** [comment]
Jay,The problems with trying to draw and edit routes seem to have vanished now that I’m using the Microsoft Edge web browser app on my iPhone and iPad.  With Edge, the waypoints move smartly and responsively when I drag them around using Edge. It’s soo much faster to make edits now. Also, when setting the starting time of a route the clock dial seems to work more reliably.In Safari, at least in iOS on my iPad and iPhone, trying to edit routes by moving a waypoint would cause it to drift around like a puck on an air hockey table. You’d have to wait for it to stop drifting before you could try moving it again.  Eventually you could get a waypoint where you wanted but it took a lot of time and was very frustrating.  Using DeepZoom to work with routes in Safari is like playing OctoDad. Anyway, problem solved with the Edge workaround.Separate question: what is the purpose of the feature “Ripple departure date offset changes to all later routes” and how is it used? Can you give an example or two? I’ve tried using it but nothing seems to be affected.Doug ***@***.*** Nov 21, 2022, at 2:13 PM, Jay Borseth ***@***.***> wrote:﻿
Also, which version of Safari are you running.  Sounds like there were WebGL problems in some Safari versions.
https://bugs.webkit.org/show_bug.cgi?id=230749
https://developer.apple.com/forums/thread/681058
Have you tried DeepZoom with Chrome?

**Comment by jaybo** [comment]
Curious.  Could you tell me the kind of iPad/iPhone you're using and the versions of Chrome and Safari which don't work?  I used to use an iPhone 6s for testing, and verified that it worked on all browsers on that device as of the last release. 

I thought that all iOS browsers were using WebKit under the hood, so it's odd they wouldn't all perform the same:
https://www.macrumors.com/2022/12/14/apple-considering-non-webkit-iphone-browsers/

The `Ripple departure date offset changes to all later routes` checkbox works like this.  Assume you have a trip with 5 routes where each route begins on a sequential day, say **Mon, Tue, Wed, Thu, Fri**.  If you're looking at the Wed route on the Routes page and check this box and THEN change the departure date for Wed +1 day your departure days will now be on:
**Mon, Tue, Thu, Fri, Sat**, so all later routes will have their departure dates also pushed back one day.

In the world of video editing, this is called a "ripple" edit.  All video clips after an insert or cut point shift in unison.

**Comment by Dougpalm** [comment]
Jay,Thanks for your reply. I’m using the first generation iPad Pro 12.9” with iOS 16.3 and an iPhone 14 Pro Max on iOS 16.3 but I’ve had the “OctoDad” problem with route editing in Safari since the trip and route planning features were first added to DeepZoom. Maybe installing Microsoft Edge yesterday on both devices had some effect because now the problem seems to be significantly reduced in Safari, both on my ipad and my iphone.  To the point I can’t really say it’s any different from using DeepZoom with Edge.  I started to make two comparison videos contrasting the issue in Safari with Edge but now I can’t reproduce the problem. Argh.On the ripple feature, I figured so much but I have not been able to make it do anything other than showing a check in the ripple boxes for the routes.  For example, I open a trip with four routes, all happening on the same day and none of them checked for ripple.  I change the third route to ripple and all the routes check boxes change to ripple.  I change the date of the third route to one day later and the date of the fourth route does not change, it stays the same as the first two.  In other words, checking the ripple box does not have any effect other than checking the ripple box for all the routes on the trip.  I tried saving the route after making the change but nothing happens.  All the ripple check box does is show a check or not a check but it has no other effect. What am I doing wrong?Doug ***@***.*** Feb 11, 2023, at 8:15 AM, Jay Borseth ***@***.***> wrote:﻿
Curious.  Could you tell me the kind of iPad/iPhone you're using and the versions of Chrome and Safari which don't work?  I used to use an iPhone 6s for testing, and verified that it worked on all browsers on that device as of the last release.
I thought that all iOS browsers were using WebKit under the hood, so it's odd they wouldn't all perform the same:
https://www.macrumors.com/2022/12/14/apple-considering-non-webkit-iphone-browsers/
The Ripple departure date offset changes to all later routes checkbox works like this.  Assume you have a trip with 5 routes where each route begins on a sequential day, say Mon, Tue, Wed, Thu, Fri.  If you're looking at the Wed route on the Routes page and check this box and THEN change the departure date for Wed +1 day your departure days will now be on:
Mon, Tue, Thu, Fri, Sat, so all later routes will have their departure dates also pushed back one day.
In the world of video editing, this is called a "ripple" edit.  All video clips after an insert or cut point shift in unison.

**Comment by jaybo** [comment]
Ripple edits only affect changes by whole days (not hours).  In your case, all of the routes are happening on the same day, and so the logic which looks for routes beginning on later days is never triggered.

The main use case is if you've planned a multi-day trip and then decide to hang out another day midway through, you can easily adjust all later routes by just incrementing the selected route by one or more days with `Ripple departure date offset changes to all later routes` enabled.

Perhaps what you're looking for is to adjust the Trip start date.  This offsets all routes by a fixed number of days.

There is no capability to adjust all routes by a fixed number of hours...

**Comment by Dougpalm** [comment]
Hmm.  Even when I change the thrid route to start several days later, the fourth route does not update when the ripple effect is on.  Maybe I need to start over with a new trip.Doug ***@***.*** Feb 11, 2023, at 10:09 AM, Jay Borseth ***@***.***> wrote:﻿
Ripple edits only affect changes by whole days (not hours).  In your case, all of the routes are happening on the same day, and so the logic which looks for routes beginning on later days is never triggered.
The main use case is if you've planned a multi-day trip and then decide to hang out another day midway through, you can easily adjust all later routes by just incrementing the selected route by one or more days with Ripple departure date offset changes to all later routes enabled.
Perhaps what you're looking for is to adjust the Trip start date.  This offsets all routes by a fixed number of days.
There is no capability to adjust all routes by a fixed number of hours...

**Comment by Dougpalm** [comment]
Jay,I started a new three day trip from scratch. In Routes, I set the ripple effect on then proceeded to add routes.The first three routes occur on the first day.  I made three routes that day so I could have two breaks along the way to my first camp. The fourth route occurs on the second day. The fifth route on the third day. All routes set with the correct starting dates and times. The whole trip saved to preserve all the route information.The trip plays out as expected, each route in proper sequence and happening on the correct dates and starting at the correct times.Double checking the routes the ripple box is still checked on all of them.Now comes the problem.  When I try to extend my stay at the first campsite by increasing route four by one day, the increase does not ripple to route five.  Don’t know what do do to make this ripple feature work!Doug ***@***.*** Feb 11, 2023, at 10:34 AM, Doug Palm ***@***.***> wrote:﻿Hmm.  Even when I change the thrid route to start several days later, the fourth route does not update when the ripple effect is on.  Maybe I need to start over with a new trip.Doug ***@***.*** Feb 11, 2023, at 10:09 AM, Jay Borseth ***@***.***> wrote:﻿
Ripple edits only affect changes by whole days (not hours).  In your case, all of the routes are happening on the same day, and so the logic which looks for routes beginning on later days is never triggered.
The main use case is if you've planned a multi-day trip and then decide to hang out another day midway through, you can easily adjust all later routes by just incrementing the selected route by one or more days with Ripple departure date offset changes to all later routes enabled.
Perhaps what you're looking for is to adjust the Trip start date.  This offsets all routes by a fixed number of days.
There is no capability to adjust all routes by a fixed number of hours...

**Comment by jaybo** [comment]
I think I see what's going on.  The ` Ripple departure date offset changes to all later routes` is hooked up to the +1/-1 buttons (which BTW are **not** visible on small mobile devices) and to the `Now` button but not to the calendar itself.  Oops.  I'll try and fix this omission.

![image](https://user-images.githubusercontent.com/1607323/218288700-f467bb9c-5ed3-4a0d-9849-7d1793f0e64e.png)

Also:
1. I was wrong about an earlier statement.  Ripple changes **will** affect routes on the same day as the selected route if they depart after the selected route.
2. The intent of the Ripple checkbox is not to leave it enabled.  Just turn it on momentarily when you want to affect the selected and later routes.

Here's a trip we can use to compare notes:  
DeepZoom trip: testRippleDeparture 
https://www.deepzoom.com/trip/veg8pevj

**Comment by jaybo** [comment]
Fixed.  Ripple works for Calendar as well as +1 / -1 buttons in next version.

**Comment by Dougpalm** [comment]
Many thanks! It will be helpful to be able to make that change in the calendar for a given route because there are no +1 or -1 buttons in the route edit mode for ripple adjustment; on either the iPad or iPhone, even in Edge. There is only a “now” button that pops up in the place where the +1 or -1 buttons would be I’m supposing.Doug ***@***.*** Feb 12, 2023, at 11:56 AM, Jay Borseth ***@***.***> wrote:﻿
Fixed.  Ripple works for Calendar as well as +1 / -1 buttons in next version.

**Comment by jaybo** [comment]
Just curious. Do the +1 / -1 buttons appear if you turn your iPad into landscape position?:

**Comment by Dougpalm** [comment]
No, that’s the typical orientation I use for DeepZoom. Here’s a screen grab.  Note, I run DeepZoom as a progressive web app instead of just bringing it up in a web browser.Doug ***@***.*** Feb 13, 2023, at 8:06 AM, Jay Borseth ***@***.***> wrote:﻿
Just curious. Do the +1 / -1 buttons appear if you turn your iPad into landscape position?:

**Comment by jaybo** [comment]
Pictures don't seem to come through unless you're editing the thread on GitHub...

**Comment by Dougpalm** [comment]
Jay,Here’s a link to that image showing the landscape view of DeepZoom running as a progressive web app on my 12.9” first generation iPad Pro on iOS 16.3. The screen shot was taken while editing a route with the ripple box checked. Note the lack of -1 and +1 buttons for incrementing the date. https://www.dropbox.com/s/hel9fzztncoxh48/Photo%20Feb%2013%202023%2C%208%2015%2053%20AM.png?dl=0Doug ***@***.*** Feb 13, 2023, at 8:56 AM, Jay Borseth ***@***.***> wrote:﻿
Pictures don't seem to come through unless you're editing the thread on GitHub...

**Comment by jaybo** [comment]
This is fixed in the next release.  +1 / -1 buttons appear whenever the display width is > 600px.  The buttons should appear on phones in landscape mode now too.

Thanks for logging this bug.   In the future, just for searchability, you may want to consider starting a new `issue` for each new topic.
