### ISSUE TITLE
Unable to Reload Saved Routes Between Sessions

### ISSUE THREAD

**Issue by OlympicDigital** [jaybo/deepzoom-blog#6]
I've been trying to create Routes to plan some trips, but the page is behaving strangely:

1.  I can't seem to get Routes to save between sessions.  I am logged in, and my Trips show up, but the Routes list does not populate as expected when I log back in or refresh the page.   The new routes remain when I go from tab to tab.  
2. if I copy a named Route, the page reverts my name to "route 1" and names the copy "route 1  copy".  
3. If I create a second Route, the first Route's name reverts to "route 1"

I get the same behavior with Firefox and Chrome and Edge.  I've disabled AdBlock and Badger for the DeepZoom site.  
Should I be able to save Routes between sessions?  Should I be able copy Routes and retain their custom names?

**Comment by jaybo** [comment]
Q1. Can you please confirm this behavior happens on version 2.4.6 or above?  The symptoms you're describing happened on some versions from > 30 days ago, before route renaming required pushing a separate button.
I just tried to duplicate your bug report on v2.4.6 without success.

Q2. Are you logged in and saving the trip between browser refreshes?  
Aside:  I've gone back and forth on whether modified but unsaved trips should be restored across a browser refresh.
Novice users want to start with a clean slate and not be carried back in time by old routes. So for now all browser refreshes result in a Trip.New.

**Comment by OlympicDigital** [comment]
Q1. I am using 2.4.6. Below is a screen shot from a New>Double
      Click>Done>Rename>Dropdown sequence.  It looks like the
      dropdown list isn't getting updated after the Route rename.
      
    Q2. I think I misunderstood the relation between Deep Zoom (DZ)
      Routes and Trips.  In other chart plotter applications, routes are
      more like DZ Trips; collections of waypoints that can saved or
      exported to a .GPX file.  It sounds like DZ Routes are not
      supposed to be persisted.  OK.   If a DZ Trip = a
      chartplotter/.GPX "Route" and a DZ Route is only a temporary,
      "unsaved trip", it might be worthwhile mentioning that in that
      italicized description for Route.  I wondered why there was no way
      to Save a Route!
    
    On further "review", I think I'm seeing another way to think of
      the DZ Trip-Route interface:
    
      The "New" button in the Trip tab is a kind of  "Clear" that
        deselects the selected Trip (and "unsaved trip") from the saved
        Trip collection.
      
      The "Active Trip" dropdown is "Load", since the active trip
        gets loaded into the Routes list and becomes the default Route.
      
      Selecting the "Edit" button in the Route tab with a saved Trip
        selected is more like "Edit Trip"
      Selecting the "Save" button in the Trip tab with an unsaved
        Route is more like "Add Trip" (kind of what I thought "New"
        would 
      
    
    Here's where things get weird for me:  If I create a new Route in
      the Routes tab and select the Trips tab, my "route 1" becomes
      "unsaved trip".  I can give it a new Trip name and save it now,
      but DZ never lets me know that my new Route is now the "candidate"
      unsaved Trip.  It would be nice to know that the "unsaved trip" is
      actually my newly minted Route!  
    
    Another odd thing is that when I select a saved Trip and go to
      the Routes tab, the selected Trip appears on the map, but hasn't
      been selected in the "route name" dropdown.  If the Routes tab is
      the place to edit routes, it seems to me that the Trip I select in
      the Trips tab should follow me to the Routes tab as the selected,
      default Route.  That way I could pick the Trip I want to edit,
      select Routes, click Edit and start moving my waypoints around. 
      Just my $0.02.
    
    Thanks for listening to my rant.  I like Deep Zoom and plan to
      use it as cruise planning tool in the future.
    Marvin
    
    On 5/20/2022 8:26 AM, Jay Borseth wrote:
    
    
      
      Q1. Can you please confirm this behavior happens on
        version 2.4.6 or above? The symptoms you're describing happened
        on some versions from > 30 days ago, before route renaming
        required pushing a separate button.
        I just tried to duplicate your bug report on v2.4.6 without
        success.
      Q2. Are you logged in and saving the trip between
        browser refreshes?
        Aside: I've gone back and forth on whether modified but unsaved
        trips should be restored across a browser refresh.
        Novice users want to start with a clean slate and not be carried
        back in time by old routes. So for now all browser refreshes
        result in a Trip.New.
      —
        Reply to this email directly, view it on GitHub, or unsubscribe.
        You are receiving this because you authored the thread.Message
          ID: ***@***.***>
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/jaybo/deepzoom-blog/issues/6#issuecomment-1133036742",
"url": "https://github.com/jaybo/deepzoom-blog/issues/6#issuecomment-1133036742",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by jaybo** [comment]
A trip is just a named container for routes, markers, and scripts, and settings.  By default, a trip doesn't contain any geometry.  But it _can_ contain one or more routes.  Each route can have a bunch of individual properties, like a line geometry, departure time, speed, color, ...  The name of the trip and any route name(s) are completely different things.

Trip.New erases everything and makes "unsaved trip" the current trip.  You can then add one or more routes, and presumably save the trip at which point you get to assign a name and public/private and other attributes.

At any point, you can "open" an already saved trip.  This newly opened trip completely replaces whatever trip was previously in existence.  

(Hmm, perhaps you'd like the ability to "merge" trips at this point?  Seems like a reasonable idea.  GPX and KML imports already allow this).

Here's a trip with 28 routes:  https://deepzoom.com/trip/bjwhbzpv
Maybe you could use this to demonstrate the renaming problem, because I'm still not seeing it.  If I rename a route, the updated name appears in the dropdown list.

**"since the active trip gets loaded into the Routes list and becomes the default Route**"  No.  Trips get loaded into the trips list.  Any routes in the trip get loaded into the routes list..

**a DZ Route is only a temporary, "unsaved trip"**,   No.  Again, it seems like you're conflating trips and routes.

Just out of curiosity, are you running DeepZoom on a phone or laptop/desktop?

**Comment by OlympicDigital** [comment]
Thanks for engaging with me on my issues and observations.to
      answer your last question first, I've been playing with DZ Trips
      and Routes on a Windows 10 PC, from Firefox.  I've embedded my
      other replies embedded in green,
      below...
    
    On 5/20/2022 7:55 PM, Jay Borseth
      wrote:
    
    
      
      A trip is just a named container for routes,
        markers, and scripts, and settings. By default, a trip doesn't
        contain any geometry. But it can contain one or more
        routes. Each route can have a bunch of individual properties,
        like a line geometry, departure time, speed, color, ... The name
        of the trip and any route name(s) are completely different
        things.
      Trip.New erases everything and makes "unsaved trip"
        the current trip. You can then add one or more routes, and
        presumably save the trip at which point you get to assign a name
        and public/private and other attributes.  The
          non-obvious thing for me was that I need to create a Trip and
          then load it with a Route.  Somehow I guess I thought
          that I would create a library of Routes and assemble them into
          Trips.  I'll try to keep in mind "Trip first then draw a
          Route".  I'm left to wonder why DZ supports multiple
          disconnected Routes. Is that the way users break a Trip into
          legs, as with your 28-route Trip?  
    
    At any point, you can "open" an already saved trip. This newly
    opened trip completely replaces whatever trip was previously in
    existence.
    
      (Hmm, perhaps you'd like the ability to "merge"
        trips at this point? Seems like a reasonable idea. GPX and KML
        imports already allow this). I guess I'd
          be more of a fan of saving Routes independently of Trips so I
          could assemble a new Trip from a library of existing Routes. 
          It seems like it would be possible to load such a Route
          library from GPX or KML files as well.
        
    
    Here's a trip with 28 routes:https://deepzoom.com/trip/bjwhbzpv
    
      
        Maybe you could use this to demonstrate the renaming problem,
        because I'm still not seeing it. If I rename a route, the
        updated name appears in the dropdown list. Try
          creating a new Route, renaming it to, say "aaa", then copying
          it.   I get "route 1" and "route 1 copy" with "aaa" as the
          selected item.  "route" and "route 1" are still in the
          dropdown.  If I then select "route 1", "aaa" disappears as
          though the new name only affected the selected item label, but
          not the item label itself.
      
      "since the active trip gets loaded into the
          Routes list and becomes the default Route" No. Trips
        get loaded into the trips list. Any routes in the trip get
        loaded into the routes list..
      a DZ Route is only a temporary, "unsaved
          trip", No. Again, it seems like you're conflating
        trips and routes.  OK, a Trip is a
          decorated collection of Routes.  It would be nice if a Route
          could be persisted independently of a Trip.  For reuse.  :-} 
      
      Just out of curiosity, are you running DeepZoom on a
        phone or laptop/desktop?
      —
        Reply to this email directly, view it on GitHub, or unsubscribe.
        You are receiving this because you authored the thread.Message
          ID: ***@***.***>
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/jaybo/deepzoom-blog/issues/6#issuecomment-1133515491",
"url": "https://github.com/jaybo/deepzoom-blog/issues/6#issuecomment-1133515491",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by jaybo** [comment]
OK. I finally replicated the renaming bug. It will be fixed in the next release.

**Comment by jaybo** [comment]
Fixed in Version 2.5.0.
